import streamlit as st
import pandas as pd
import joblib

# Page Config
st.set_page_config(
    page_title="Cervical Cancer Risk Prediction",
    page_icon="🩺",
    layout="wide"
)

# Load Model
model = joblib.load("cervical_cancer_model.pkl")
scaler = joblib.load("scaler.pkl")

# Custom CSS
st.markdown("""
<style>

.stButton > button {
    width:100%;
    height:60px;
    border-radius:15px;
    background:linear-gradient(90deg,#1976D2,#42A5F5);
    color:white;
    font-size:20px;
    font-weight:bold;
    border:none;
}

.stButton > button:hover {
    transform:scale(1.02);
}

</style>
""", unsafe_allow_html=True)

# Sidebar
with st.sidebar:

    st.title("🏥 Health Analytics Dashboard")

    st.info("""
### Cervical Cancer Risk Assessment

This intelligent screening system uses machine learning to estimate cervical cancer risk based on patient history and diagnostic indicators.
""")

    st.markdown("""
### 🔬 Model Details
- Algorithm: XGBoost
- Features: 33
- Preprocessing: StandardScaler
- Output: Risk Probability

### 📋 Parameters Analyzed
- Personal Information
- Smoking History
- Contraceptive Usage
- IUD Usage
- STD History
- Diagnostic Results
""")

    st.warning("""
⚠️ Educational Project

This tool is intended for educational and research purposes only.
""")

    st.markdown("---")
    st.write("👩‍💻 Developed by")
    st.write("**Kalyani M G**")

# Main Header
st.markdown("""
<h1 style='text-align:center;color:#1976D2;'>
🩺 Cervical Cancer Risk Prediction
</h1>

<p style='text-align:center;font-size:18px;color:gray;'>
Machine Learning Based Healthcare Risk Assessment
</p>
""", unsafe_allow_html=True)

st.markdown("---")

# Disclaimer
st.warning("""
⚠️ Medical Disclaimer

This application is intended for educational and research purposes only.

Predictions generated by this machine learning model should not be considered a medical diagnosis.

Please consult a qualified healthcare professional for medical advice and treatment decisions.
""")



# Features
features = [
    'Age',
    'Number of sexual partners',
    'First sexual intercourse',
    'Num of pregnancies',
    'Smokes',
    'Smokes (years)',
    'Smokes (packs/year)',
    'Hormonal Contraceptives',
    'Hormonal Contraceptives (years)',
    'IUD',
    'IUD (years)',
    'STDs',
    'STDs (number)',
    'STDs:condylomatosis',
    'STDs:cervical condylomatosis',
    'STDs:vaginal condylomatosis',
    'STDs:vulvo-perineal condylomatosis',
    'STDs:syphilis',
    'STDs:pelvic inflammatory disease',
    'STDs:genital herpes',
    'STDs:molluscum contagiosum',
    'STDs:AIDS',
    'STDs:HIV',
    'STDs:Hepatitis B',
    'STDs:HPV',
    'STDs: Number of diagnosis',
    'Dx:Cancer',
    'Dx:CIN',
    'Dx:HPV',
    'Dx',
    'Hinselmann',
    'Schiller',
    'Citology'
]

binary_features = [
    'Smokes',
    'Hormonal Contraceptives',
    'IUD',
    'STDs',
    'Dx:Cancer',
    'Dx:CIN',
    'Dx:HPV',
    'Dx',
    'Hinselmann',
    'Schiller',
    'Citology',
    'STDs:cervical condylomatosis',
    'STDs:vaginal condylomatosis',
    'STDs:vulvo-perineal condylomatosis',
    'STDs:syphilis',
    'STDs:pelvic inflammatory disease',
    'STDs:genital herpes',
    'STDs:molluscum contagiosum',
    'STDs:AIDS',
    'STDs:HIV',
    'STDs:Hepatitis B',
    'STDs:HPV'
]

st.subheader("📋 Patient Information")

inputs = {}

col1, col2 = st.columns(2)

for i, feature in enumerate(features):

    with col1 if i % 2 == 0 else col2:

        if feature in binary_features:

            inputs[feature] = (
                1 if st.selectbox(
                    feature,
                    ["No", "Yes"],
                    key=feature
                ) == "Yes"
                else 0
            )

        else:

            inputs[feature] = st.number_input(
                feature,
                min_value=0.0,
                value=0.0,
                step=0.1,
                format="%.1f",
                key=feature
            )

# Prediction
if st.button("🔍 Predict Risk"):

    with st.spinner("Analyzing patient data..."):

        patient = pd.DataFrame([inputs])

        patient_scaled = scaler.transform(patient)

        prediction = model.predict(patient_scaled)

        probability = model.predict_proba(patient_scaled)[0][1]

    st.markdown("---")

    st.subheader("📊 Prediction Results")

    st.markdown(f"""
    <div style="
    background:linear-gradient(90deg,#0E2A47,#1565C0);
    padding:25px;
    border-radius:15px;
    color:white;
    margin-bottom:20px;
    box-shadow:0 4px 10px rgba(0,0,0,0.2);
    ">
        <h4 style="margin:0;">Risk Probability</h4>
        <h1 style="margin-top:10px;">
            {probability*100:.2f}%
        </h1>
    </div>
    """, unsafe_allow_html=True)

    st.progress(float(probability))

    if probability < 0.30:
        st.success("🟢 Low Risk")

    elif probability < 0.70:
        st.warning("🟡 Moderate Risk")

    else:
        st.error("🔴 High Risk")

    st.info("""
📌 Important Note

This result is generated using a machine learning model trained on historical clinical data.

It should not be used as a substitute for professional medical diagnosis or treatment.
""")

# Footer
st.markdown("---")

st.caption(
    "© 2026 Cervical Cancer Risk Prediction System | Developed by Kalyani M G"
)
