import streamlit as st
import pandas as pd
import joblib

# Page Config
st.set_page_config(
    page_title="Cervical Cancer Risk Prediction",
    page_icon="🩺",
    layout="wide"
)

# Load Model
model = joblib.load("cervical_cancer_model.pkl")
scaler = joblib.load("scaler.pkl")

# Custom CSS
st.markdown("""
<style>

.stButton > button {
    width:100%;
    height:60px;
    border-radius:15px;
    background:linear-gradient(90deg,#1976D2,#42A5F5);
    color:white;
    font-size:20px;
    font-weight:bold;
    border:none;
}

.stButton > button:hover {
    transform:scale(1.02);
}

</style>
""", unsafe_allow_html=True)

# Sidebar
with st.sidebar:

    st.title("🏥 Health Analytics Dashboard")

    st.info("""
### Cervical Cancer Risk Assessment

This intelligent screening system uses machine learning to estimate cervical cancer risk based on patient history and diagnostic indicators.
""")

    st.markdown("""
### 📊 System Overview
- Clinical Risk Assessment
- 33 Health Indicators
- Patient History Analysis
- Risk Probability Estimation

### 📋 Parameters Analyzed
- Personal Information
- Smoking History
- Contraceptive Usage
- IUD Usage
- STD History
- Diagnostic Results
""")

    st.warning("""
⚠️ Educational Project

This tool is intended for educational and research purposes only.
""")

    st.markdown("---")
    st.write("👩‍💻 Developed by")
    st.write("**Kalyani M G**")

# Main Header
st.markdown("""
<h1 style='text-align:center;color:#1976D2;'>
🩺 Cervical Cancer Risk Prediction
</h1>

<p style='text-align:center;font-size:18px;color:gray;'>
Clinical Risk Assessment Support System
</p>
""", unsafe_allow_html=True)

st.markdown("---")

# Disclaimer
st.warning("""
⚠️ Medical Disclaimer

This application is intended for educational and research purposes only.

Predictions generated by this machine learning model should not be considered a medical diagnosis.

Please consult a qualified healthcare professional for medical advice and treatment decisions.
""")



# Features
features = [
    'Age',
    'Number of sexual partners',
    'First sexual intercourse',
    'Num of pregnancies',
    'Smokes',
    'Smokes (years)',
    'Smokes (packs/year)',
    'Hormonal Contraceptives',
    'Hormonal Contraceptives (years)',
    'IUD',
    'IUD (years)',
    'STDs',
    'STDs (number)',
    'STDs:condylomatosis',
    'STDs:cervical condylomatosis',
    'STDs:vaginal condylomatosis',
    'STDs:vulvo-perineal condylomatosis',
    'STDs:syphilis',
    'STDs:pelvic inflammatory disease',
    'STDs:genital herpes',
    'STDs:molluscum contagiosum',
    'STDs:AIDS',
    'STDs:HIV',
    'STDs:Hepatitis B',
    'STDs:HPV',
    'STDs: Number of diagnosis',
    'Dx:Cancer',
    'Dx:CIN',
    'Dx:HPV',
    'Dx',
    'Hinselmann',
    'Schiller',
    'Citology'
]

binary_features = [
    'Smokes',
    'Hormonal Contraceptives',
    'IUD',
    'STDs',

    'STDs:condylomatosis',

    'STDs:cervical condylomatosis',
    'STDs:vaginal condylomatosis',
    'STDs:vulvo-perineal condylomatosis',
    'STDs:syphilis',
    'STDs:pelvic inflammatory disease',
    'STDs:genital herpes',
    'STDs:molluscum contagiosum',
    'STDs:AIDS',
    'STDs:HIV',
    'STDs:Hepatitis B',
    'STDs:HPV',

    'Dx:Cancer',
    'Dx:CIN',
    'Dx:HPV',
    'Dx',
    'Hinselmann',
    'Schiller',
    'Citology'
]

integer_features = [
    'Age',
    'Number of sexual partners',
    'First sexual intercourse',
    'Num of pregnancies',
    'STDs (number)',
    'STDs: Number of diagnosis'
]

display_names = {
    'Age': 'Age (Years)',
    'Number of sexual partners': 'Number of Sexual Partners',
    'First sexual intercourse': 'Age at First Sexual Intercourse',
    'Num of pregnancies': 'Number of Pregnancies',

    'Smokes': 'Smoking History',
    'Smokes (years)': 'Years of Smoking',
    'Smokes (packs/year)': 'Smoking Exposure (Pack-Years)',

    'Hormonal Contraceptives': 'Uses Hormonal Contraceptives',
    'Hormonal Contraceptives (years)': 'Years of Contraceptive Use',

    'IUD': 'Uses Intrauterine Device (IUD)',
    'IUD (years)': 'Years of IUD Use',

    'STDs': 'History of STDs',
    'STDs (number)': 'Number of STD Diagnoses',

    'STDs:condylomatosis': 'Genital Warts',
    'STDs:cervical condylomatosis': 'Cervical Genital Warts',
    'STDs:vaginal condylomatosis': 'Vaginal Genital Warts',
    'STDs:vulvo-perineal condylomatosis': 'Vulva/Perineal Genital Warts',

    'STDs:syphilis': 'History of Syphilis',
    'STDs:pelvic inflammatory disease': 'Pelvic Inflammatory Disease',
    'STDs:genital herpes': 'Genital Herpes',
    'STDs:molluscum contagiosum': 'Molluscum Contagiosum',

    'STDs:AIDS': 'AIDS Diagnosis',
    'STDs:HIV': 'HIV Infection',
    'STDs:Hepatitis B': 'Hepatitis B Infection',
    'STDs:HPV': 'HPV Infection',

    'STDs: Number of diagnosis': 'Total STD Diagnoses',

    'Dx:Cancer': 'Previous Cervical Cancer Diagnosis',
    'Dx:CIN': 'Previous Cervical Lesion (CIN)',
    'Dx:HPV': 'Previous HPV Diagnosis',
    'Dx': 'Any Previous Cervical Diagnosis',

    'Hinselmann': 'Positive Hinselmann Test',
    'Schiller': 'Positive Schiller Test',
    'Citology': 'Abnormal Pap Smear Result'
}
help_text = {
    'Smokes (packs/year)': 'Measures cumulative smoking exposure.',
    'Dx': 'Any previous diagnosis related to cervical disease.',
    'Dx:CIN': 'Precancerous changes in cervical cells.',
    'Citology': 'Result of Pap smear examination.',
    'Hinselmann': 'Cervical examination test result.',
    'Schiller': 'Iodine-based cervical screening test result.',
    'STDs:HPV': 'Human Papillomavirus infection history.'
}

st.subheader("📋 Patient Information")

integer_features = [
    'Age',
    'Number of sexual partners',
    'First sexual intercourse',
    'Num of pregnancies',
    'STDs (number)',
    'STDs: Number of diagnosis'
]

inputs = {}

col1, col2 = st.columns(2)

for i, feature in enumerate(features):

    label = display_names.get(feature, feature)
    tooltip = help_text.get(feature, None)

    with col1 if i % 2 == 0 else col2:

        if feature in binary_features:

            inputs[feature] = (
                1 if st.selectbox(
                    label,
                    ["No", "Yes"],
                    help=tooltip,
                    key=feature
                ) == "Yes"
                else 0
            )

        else:

            if feature in integer_features:

                default_value = 0

                if feature == "Age":
                    default_value = 25
                elif feature == "First sexual intercourse":
                    default_value = 18
                elif feature == "Number of sexual partners":
                    default_value = 1

                inputs[feature] = st.number_input(
                    label,
                    min_value=0,
                    value=default_value,
                    step=1,
                    help=tooltip,
                    key=feature
                )

            else:

                inputs[feature] = st.number_input(
                    label,
                    min_value=0.0,
                    value=0.0,
                    step=0.1,
                    format="%.1f",
                    help=tooltip,
                    key=feature
                )
# Prediction
if st.button("🔍 Predict Risk"):

    with st.spinner("Analyzing patient data..."):

        patient = pd.DataFrame([inputs])

        patient_scaled = scaler.transform(patient)

        prediction = model.predict(patient_scaled)

        probability = model.predict_proba(patient_scaled)[0][1]

    st.markdown("---")

    st.subheader("📊 Prediction Results")

    st.markdown(f"""
    <div style="
    background:linear-gradient(90deg,#0E2A47,#1565C0);
    padding:25px;
    border-radius:15px;
    color:white;
    margin-bottom:20px;
    box-shadow:0 4px 10px rgba(0,0,0,0.2);
    ">
        <h4 style="margin:0;">Risk Probability</h4>
        <h1 style="margin-top:10px;">
            {probability*100:.2f}%
        </h1>
    </div>
    """, unsafe_allow_html=True)

    st.progress(float(probability))

    if probability < 0.30:
        st.success("🟢 Low Risk")

    elif probability < 0.70:
        st.warning("🟡 Moderate Risk")

    else:
        st.error("🔴 High Risk")

    st.info("""
📌 Important Note

This result is generated using a machine learning model trained on historical clinical data.

It should not be used as a substitute for professional medical diagnosis or treatment.
""")


st.markdown("---")

with st.expander("📖 View Project Information"):

    st.write("""
    **Project:** Cervical Cancer Risk Prediction System

    This application uses machine learning to estimate cervical cancer risk
    based on patient history and clinical indicators.

    **Technologies**
    - Python
    - Streamlit
    - Pandas
    - Scikit-Learn
    - XGBoost

    **Features**
    - 33 Clinical Parameters
    - Risk Probability Estimation
    - Interactive Healthcare Dashboard

    **Developer**
    Kalyani M G
    """)

st.markdown("---")

st.caption(
    "© 2026 Cervical Cancer Risk Prediction System | Developed by Kalyani M G"
)
